config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/about'

  get 'pages/contact'

  get 'products/index'

  get 'products/show'

  get 'admins/index'

  root 'pages#index'

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout 'products' 
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	layout 'products'
  def index
  end

  def show
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/index.html.erb
<h1>Admins#index</h1>
<p>Find me in app/views/admins/index.html.erb</p>
<p>estoi en admins index</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NuevaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NuevaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render  'shared/navbar' %>  
<%= yield %>

</body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NuevaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'products' ,  'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
product

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/shared/_navbar.html.erb
<%= link_to 'Admin', admins_index_path %>
<%= link_to 'Home', pages_index_path %>
<%= link_to 'About', pages_about_path %>
<%= link_to 'Contact', pages_contact_path %>
<%= link_to 'Products', products_index_path %>
<%= link_to 'Show', products_show_path, data: {no_turbolinks: true} %>